import Link from "next/link"
//import globals.css
import "./globals.css"
import Image from "next/image"
//import font awesome
import "@fortawesome/fontawesome-svg-core/styles.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html  lang="en" data-theme="lemonade" >
      <body>        
        {/* area header */}
        <header>
          {/* area banner/image */}
          {/* <img src="../images/tekno banner.png" alt="LOGO UTI" /> */}
          <Image src={"/images/tekno banner.png"} alt="Logo UTI" width={320} height={60} priority></Image>

          {/* area menu */}
          <nav className="text-center mt-5 flex justify-end	mr-5">
            <Link href={"/"} className="bg-green-900 hover:bg-green-950 text-white rounded-full px-5 py-2.5 mr-3 w-52">Data Mahasiswa</Link>
            <Link href={"/"} className="bg-green-900 hover:bg-green-950 text-white rounded-full px-5 py-2.5 ml-3 w-52">Log Data Mahasiswa</Link>
          </nav>
        </header>

        {/* area konten */}
        <section className="m-5">{children}</section>
        
        
        {/* area footer */}
        <footer className="flex justify-center bg-color1 text-color3-1 py-15x">
          Copyright &copy; 2024 - Jhoshe Maechel
        </footer>
      </body>
    </html>
  )
}
